spring.application.name= backend

spring.datasource.url= jdbc:mysql://localhost:3306/stt_db
spring.datasource.username=root
spring.datasource.password=swaS[ik12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
deepgram.api.key=${deepgram.api.key}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.port=8080